version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: healthmate_ai_db
    environment:
      POSTGRES_DB: healthmate_ai_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    volumes:
      - ./backend/database:/docker-entrypoint-initdb.d
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d healthmate_ai_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: healthmate_ai_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/healthmate_ai_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: healthmate_ai_frontend
    ports:
      - "3000:80" # Host port is 3000, container's port is 80
    depends_on:
      backend:
        condition: service_started # Frontend only needs backend to start
    volumes:
      - ./frontend:/app

volumes:
  db_data: